version: '3'

services:
  concourse-db:
    image: postgres
    volumes:
    - /mnt/persist/pg-data:/database
    environment:
    - PGDATA=/database
    env_file:
    - secrets.env

  concourse-web:
    image: concourse/concourse
    command: web
    restart: always
    links: [concourse-db]
    depends_on: [concourse-db]
    ports: ["80:80"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_BIND_PORT=80
    - CONCOURSE_EXTERNAL_URL=http://127.0.0.1:80
    - CONCOURSE_PEER_URL=http://127.0.0.1:80
    env_file:
    - secrets.env

  concourse-worker:
    image: concourse/concourse
    command: worker
    privileged: true
    restart: always # Workers sometimes die w/ btr fs mount errors ¯\_(ツ)_/¯
    links: [concourse-web]
    depends_on: [concourse-web]
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK
    - CONCOURSE_EXTERNAL_URL=http://127.0.0.1:80
    - CONCOURSE_PEER_URL=http://127.0.0.1:80