#!/bin/bash
set -eux

# Generate keys in the directory where the script is
RELATIVE_SCRIPT_DIR=$( dirname "${BASH_SOURCE[0]}" )
ABSOLUTE_SCRIPT_DIR=$( cd ${RELATIVE_SCRIPT_DIR} && pwd )
cd ${ABSOLUTE_SCRIPT_DIR}

mkdir -p keys/web keys/worker

yes | ssh-keygen -t rsa -f ./keys/web/tsa_host_key -N ''
yes | ssh-keygen -t rsa -f ./keys/web/session_signing_key -N ''

yes | ssh-keygen -t rsa -f ./keys/worker/worker_key -N ''

cp ./keys/worker/worker_key.pub ./keys/web/authorized_worker_keys
cp ./keys/web/tsa_host_key.pub ./keys/worker
