#!/usr/bin/env bash

set -eux

cd "$(dirname "$0")"

install-chef() {
    apt update
    apt install -y wget build-essential ruby2.3 ruby2.3-dev

    curl -sLO "https://omnitruck.chef.io/install.sh" | bash -s 13.6
    gem install --no-rdoc --no-ri berkshelf
}

command -v chef-client || install-chef

git fetch
git checkout -f origin/master

berks vendor cookbooks

chef-client -l debug -zr 'role[main]'
